repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
      - id: mypy
        args: [--show-error-codes]
        name: mypy AutoPyTorch
        files: autoPyTorch/.*
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        name: flake8 AutoPyTorch
        files: autoPyTorch/.*
        additional_dependencies:
          - flake8-print==3.1.4
          - flake8-import-order
      - id: flake8
        name: flake8 tests
        files: test/.*
        additional_dependencies:
          - flake8-print==3.1.4
          - flake8-import-order
